// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import (
	worker "github.com/doitintl/go-modules/worker"
	mock "github.com/stretchr/testify/mock"
)

// WorkerPool is an autogenerated mock type for the WorkerPool type
type WorkerPool struct {
	mock.Mock
}

// AddTask provides a mock function with given fields: task
func (_m *WorkerPool) AddTask(task worker.Task) {
	_m.Called(task)
}

// AddWorkers provides a mock function with given fields: count
func (_m *WorkerPool) AddWorkers(count int) {
	_m.Called(count)
}

// RemoveWorkers provides a mock function with given fields: count
func (_m *WorkerPool) RemoveWorkers(count int) {
	_m.Called(count)
}

// Stop provides a mock function with given fields:
func (_m *WorkerPool) Stop() {
	_m.Called()
}

// TaskChannel provides a mock function with given fields:
func (_m *WorkerPool) TaskChannel() chan worker.Task {
	ret := _m.Called()

	var r0 chan worker.Task
	if rf, ok := ret.Get(0).(func() chan worker.Task); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan worker.Task)
		}
	}

	return r0
}

// WorkersCount provides a mock function with given fields:
func (_m *WorkerPool) WorkersCount() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

type NewWorkerPoolT interface {
	mock.TestingT
	Cleanup(func())
}

// NewWorkerPool creates a new instance of WorkerPool. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewWorkerPool(t NewWorkerPoolT) *WorkerPool {
	mock := &WorkerPool{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
